name: Zoen to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "TOKEN_DISCORD=${{ secrets.TOKEN_DISCORD }}" > .env

      - name: Initialize bot
        run: make initialize

      - name: Stop previous bot
        run: pm2 stop bot || true

      - name: Start bot with PM2
        run: pm2 start make --name bot -- run

      - name: Save PM2 process list
        run: pm2 save