name: Zoen to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "TOKEN_DISCORD=${{ secrets.TOKEN_DISCORD }}" >> .env

      - name: Initialize bot
        run: make initialize

      - name: Deploy with PM2
        run: |
          pm2 stop all || true
          pm2 start make --name bot -- run
          pm2 save